CREATE TABLE Admin (
  email VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  firstName VARCHAR(25) NOT NULL,
  lastName VARCHAR(25) NOT NULL,
  PRIMARY KEY (email)
);

CREATE TABLE File (
  id INT UNSIGNED AUTO_INCREMENT,
  editId INT UNSIGNED,
  language VARCHAR(50) NOT NULL,
  speaker VARCHAR(100) DEFAULT NULL,
  path VARCHAR(256) NOT NULL,
  timeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX ix_File_language (language),
  INDEX ix_File_timeCreated (timeCreated)
);

CREATE TABLE Edit (
  id INT UNSIGNED AUTO_INCREMENT,
  fileId INT UNSIGNED,
  timeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  transcription TEXT NOT NULL,
  status ENUM('ACCEPTED', 'REJECTED', 'SUBMITTED') NOT NULL DEFAULT 'SUBMITTED',
  PRIMARY KEY (id),
  INDEX ix_Edit_timeCreated (timeCreated),
  CONSTRAINT fk_Edit_fileId FOREIGN KEY (fileId) REFERENCES File (id) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE File
ADD FOREIGN KEY fk_File_editId (editId) REFERENCES Edit (id) ON DELETE CASCADE ON UPDATE CASCADE;

